[tox]
min_version = 4
envlist = test_package, checks
skipsdist = True

[testenv]
basepython = python
install_command = pip install {opts} {packages}
setenv =
    PYTHONPATH=.:src
    PYTHONHASHSEED=0

[testenv:test_package]
deps =
    -r requirements.txt
    -r test_requirements.txt
commands =
    python src/train.py
    pytest -s -vv {posargs:tests/}

[testenv:checks]
deps =
    -r typing_requirements.txt
commands =
    flake8 src tests
    isort --check-only --profile black src tests
    black --check src tests
